# Use official Python image as a base
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the Python application
COPY app.py /app/

# Command to run the application
CMD ["python", "app.py"]

